### ISSUE TITLE
negative effects in uplift/metrics/ranking.py

### ISSUE THREAD

**Issue by pianonyy** [psarka/uplift#5]
What does "negative effects" mean in this case?

**Comment by psarka** [comment]
Hi, a quick answer (maybe I'll make a proper explanation with pictures later):

Say you send a promotion (`t=1`) and expect to change the user's response from not purchase (`y=0`) to purchase (`y=1`). However, particular group of users are very unhappy to receive promotions, so they decide not purchase after receiving promotion, even though they would have purchased otherwise. This is called "negative effect".

When computing the optimal uplift curve, you can choose whether to take negative effects into account. If you don't, the curve goes only up (the more you promote, the more they purchase), while if you do, the curve goes up more, but then goes down as well (when you reach the "negative effect" group).

**Comment by pianonyy** [comment]
Thanks so much for rich message. But I also wants to find out, should I use negative uplifts in the optimal curve or not. And which cases bring these uplifts? I think it helps me to understand the uplift curve behavior on my plots 
![100000gini](https://user-images.githubusercontent.com/48867176/75607033-0af44980-5b04-11ea-9faa-ad6132df53ef.png)
![20000000_entropy](https://user-images.githubusercontent.com/48867176/75607035-0b8ce000-5b04-11ea-8260-d1624fa3e0ee.png)
![100000000_entropy](https://user-images.githubusercontent.com/48867176/75607036-0c257680-5b04-11ea-84e7-6dfa5ab6e0dd.png)

**Comment by psarka** [comment]
If you can't choose which optimal curve to use, then I would recommend not using them at all - just compare your model with the baseline and try to estimate the expected benefit of your treatment.

From what I see, your uplift_entropy models look much better then the uplift_gini, and they have a decent uplift (you can get almost all responses by targeting 20% of users). Whatever is the theoretical maximum is not of much interest.
